export const HOME_SCREEN = 'lxm.HomeScreen'
export const PLAY_DETAIL_SCREEN = 'lxm.PlayDetailScreen'
export const SONGLIST_DETAIL_SCREEN = 'lxm.SonglistDetailScreen'
export const SINGER_DETAIL_SCREEN = 'lxm.SingerDetailScreen'
export const ALBUM_DETAIL_SCREEN = 'lxm.AlbumDetailScreen'
export const COMMENT_SCREEN = 'lxm.CommentScreen'
export const AUDIOBOOK_ALBUM_DETAIL_SCREEN = 'lxm.AudiobookAlbumDetailScreen'
export const AUDIOBOOK_ANCHOR_DETAIL_SCREEN = 'lxm.AudiobookAnchorDetailScreen'
export const VERSION_MODAL = 'lxm.VersionModal'
export const PACT_MODAL = 'lxm.PactModal'
export const SYNC_MODE_MODAL = 'lxm.SyncModeModal'
// export const SETTING_SCREEN = 'lxm.SettingScreen'
// export const TOAST_SCREEN = 'lxm.ToastScreen'

